### ISSUE TITLE
Trailing whitespace in markdown

### ISSUE THREAD

**Issue by sjauld** [terraform-docs/terraform-docs#296]
**Describe the bug**

Whitespace is added to the end of lines in markdown

**To Reproduce**

1. Create `main.tf`

```
/*
* This is just
* an example
*/
```

2. `terraform-docs markdown . > README.md`

README.md ends up with two spaces after "This is just" and two line breaks after "No output."

**Expected behavior**

README.md has not trailling spaces and only a single trailling line break

**Version information:**

`terraform-docs version v0.0.0- v0.9.1 darwin/amd64 BuildDate: 2020-04-02T23:00:25+0100`

**Additional context**

**Comment by khos2ow** [comment]
@sjauld adding the tailing `<space><space>` at the end of lines in Markdown format is by design, Considering your example above, what you intended as a comment was "two lines"

```text
This is just
an example
```

It was placed in two lines because of multiple reasons: wrapping long lines, end of paragraph, etc. Markdown engine doesn't render new line (basically single `\n`) as a full carriage-return mechanism and rather ignores it, so the result of the example above in markdown becomes:

```text
This is just an example
```

But if there is a trailing `<space><space>` at the end of the line, Markdown engines will treat it as a full carriage-return. And that's the reason we put extra double space at the end of markdown lines. Note that it is not added when the next line is empty, or part of a ordered/unordered list, or table, ...

**Comment by sjauld** [comment]
Ok, a slightly more relevant example that maybe explains my use case better:


`main.tf`
```
/*
* Herein lies a length description of what is going on in this module. Since the
* documentation will be referenced by developers working within this repo, I
* prefer to keep line widths to the traditional 80 characters.
*
* If I wish to denote a paragraph break, I will simply do exactly what I would
* have done in markdown, namely, insert a couple of line breaks.
*
* Also, I don't want the double line break at the end of the document.
*/
```

I don't need my comments to be "reformatted" into markdown because I'm already writing them in markdown - "reformatting" them breaks the markdown by adding this extra whitespace.

I guess this could be a feature request rather than a bug if reformatting was really the intended use case - it didn't occur to me that anyone would want this.

Also, is the double line break at the end of the document part of the same issue or should I split it out?

**Comment by iancward** [comment]
It would be nice if the extra spaces could be optional. In my scenario, I break the lines in a block so that it will fit in an editor screen (per markdown lint); however, I _want_ them rendered as a proper paragraph together, without the newlines (that's why Markdown lets you break paragraphs like this).

**Comment by khos2ow** [comment]
Apology for late response. I see both of your points and they are actually quite valid. In order to not break the backward compatibility for anyone already relies on this I'm thinking to put this behind a flag, such as `--header-line-ending=bool` (I don't like the name of the flag just yet, but something along these lines), which will be `true` by default (adds `<space><space>`) and you can turn it off by `false` to keep the line ending as it was written.

Does this make sense as a path forward?

**Comment by khos2ow** [comment]
> Also, is the double line break at the end of the document part of the same issue or should I split it out?

@sjauld do you refer to this line `* Also, I don't want the double line break at the end of the document.` in your latest example regarding the double line break?

**Comment by iancward** [comment]
Would that `header-line-ending` also be available in the config file? If so, I think that's a great way to solve this in a non-breaking manner.

**Comment by khos2ow** [comment]
Yes, basically from now on (since we have a config file) every new flag will end up in config file and vice versa.

**Comment by wlonkly** [comment]
Was going to +1, but wanted to add: this two-spaces behavior is also present in v0.10.0-rc.1 _even if the source is already Markdown_ -- ie if you have docs.md:

```
───────┬──────────────────────────────────────────────────────────────────────────────────────────
       │ File: docs.md
───────┼──────────────────────────────────────────────────────────────────────────────────────────
   1   │ ##•test␊
   2   │ ␊
   3   │ This•is•some•markdown␊
   4   │ that•spans•several•lines␊
   5   │ but•it•is•prose•and•not␊
   6   │ poetry.␊
   7   │ ␊
───────┴──────────────────────────────────────────────────────────────────────────────────────────
```

and then you `terraform-docs --header-from docs.md markdown . > README.md`, then the resulting Markdown has hard line breaks (thanks to whitespace) at those points:

```
───────┬──────────────────────────────────────────────────────────────────────────────────────────
       │ File: README.md
───────┼──────────────────────────────────────────────────────────────────────────────────────────
   1   │ ##•test␊
   2   │ ␊
   3   │ This•is•some•markdown••␊
   4   │ that•spans•several•lines••␊
   5   │ but•it•is•prose•and•not••␊
   6   │ poetry.␊
```

Regardless of how we think this should work with comments in terraform files, I think terraform-docs should _never_ modify literal Markdown that it is provided!

I think this might be a good place to break reverse-compatibility: if the user is using Terraform comments as the header source, then continue the previous behavior, but if the user is using the new-to-0.10 capability of using straight Markdown as header source, the Markdown should be unmodified.

**Comment by khos2ow** [comment]
Thank you folks for your patience.

> Also, is the double line break at the end of the document part of the same issue

This was done in #336. And I'll be opening up a new PR shortly for the main issue here (double-spaces at the end of the lines).

**Comment by aston-r** [comment]
> And I'll be opening up a new PR shortly for the main issue here (double-spaces at the end of the lines).
@khos2ow  That would be really great! I am also looking forward to these changes

**Comment by khos2ow** [comment]
I just opened #429 (after a very long delay!) which should address this. In summary we're never going to alter line-endings of headers and assume whatever is extracted _is_ intended as it. Please let us know if you have any comments or suggestions.
