### ISSUE TITLE
Document security measures

### ISSUE THREAD

**Issue by Olgoetz** [terraform-docs/terraform-docs#298]
**Is your feature request related to a problem? Please describe.**

I did not found any information for security measures: How is it ensured that no malicious code is embedded?

**Describe the solution you'd like**

A short overview what security measures are taken.

**Describe alternatives you've considered**

I looked into the contribution guideline.

**Comment by tbugfinder** [comment]
Could you share a repo / content which matches your requirement?

**Comment by Olgoetz** [comment]
Basically I want to make sure that new code is clean and secure.
I thought I could find the information here:

https://github.com/terraform-docs/terraform-docs/blob/master/CONTRIBUTING.md
Create a Pull Request for your contribution by following the instructions in the pull request template here.

But the pull request template leads to a 404 error.

**Comment by khos2ow** [comment]
Thank you @Olgoetz for your interest in the project.

> How is it ensured that no malicious code is embedded?

Since this is an open source project and everything goes through a code review process it can be audited in the later times by interested parties to see the actual code base.

The release process is also absolutely transparent and opensource to prevent in tampering with final artifacts (released binaries or docker image) and as such every release contains a checksum of the released assets, which is absolutely recommended to be used when downloading a binary. This will further ensures there has not been any tampering with the released binary.

> https://github.com/terraform-docs/terraform-docs/blob/master/CONTRIBUTING.md
Create a Pull Request for your contribution by following the instructions in the pull request template here.
>
> But the pull request template leads to a 404 error.

That's actually a good find, historically that link has been working and I assume at some point GitHub has changed the endpoint. If you look closely the current broken link is `/pull` but the actual working link is `/pulls`.

**Comment by Olgoetz** [comment]
Thanks a lot for your comprehensive answer.
