### ISSUE TITLE
Resource links are bad

### ISSUE THREAD

**Issue by grimm26** [terraform-docs/terraform-docs#390]
### Describe the bug
The table of resource links that is generated are all bad links because terraform-docs did not fully resolve my version pin of `"~> 3.0"` so all of the links have `3.0` as the version which is bad.  

E.g.  [aws_caller_identity](https://registry.terraform.io/providers/hashicorp/aws/3.0/docs/data-sources/caller_identity)

It might be better to just use `latest` instead of a version, but you could also just fully resolve the version pin.

### How can we reproduce it?
Specify a version pin like this.
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}
```

### Environment information
`terraform-docs version v0.11.0 darwin/amd64 BuildDate: 2021-02-11T00:35:43+0000`

**Comment by khos2ow** [comment]
Thank you @grimm26 for reporting this! I'm gonna try to see if we can actually discover the version properly, otherwise as you suggested we might need to fall back on `latest` (which unfortunately might not be very accurate intention of users)

**Comment by khos2ow** [comment]
Due to complexity of [version constraints](https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax) and the fact that there's no way to discover the exact version in almost all of those cases there offline, what I think the best approach as a way forward is if specified version is:

- `= x.y.z` (fixed version): extract that fixed version and use it for the link
- anything else (dynamic ranges, pessimistic constraint, etc): use `latest` for the link (which might not be completely accurate for some use-cases, but at least the links are never broken)

And maybe potentially show the requested version in some shape or form in the output.

@grimm26  what do you think about this, as a way forward to solve the issue?

**Comment by grimm26** [comment]
That's fine by me.
