### ISSUE TITLE
Comments markdown on Bitbucket are not supported

### ISSUE THREAD

**Issue by michelzanini** [terraform-docs/terraform-docs#463]
### What problem are you facing?

Bitbucket Cloud supports Markdown format, but a modified version of the standard.
On Bitbucket, comments with `<!-- BEGIN_TF_DOCS -->` appear on the UI and do not stay hidden.

To keep them hidden one can use this format:

```
[//]: # (BEGIN_TF_DOCS)
{{ .Content }} 
[//]: # (END_TF_DOCS)
```

However, when I tried to use:

```
output:
  file: "README.md"
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }} 
    [//]: # (END_TF_DOCS)
```

It didn't work as it expects that the comments format is always `<!-- BEGIN_TF_DOCS -->` .

### How could terraform-docs help solve your problem?

terraform-docs could support other formats of comments for start / end demarcations, like the one above which works for Bitbucket.

**Comment by khos2ow** [comment]
This is a really good suggestion! To clarify the _begin_ comment format can be anything as long as it starts with `<!--` (up to now obviously and we're going to incorporate your suggestion) and it doesn't have to be exactly `<!-- BEGIN_TF_DOCS -->` (its default value.)

**Comment by khos2ow** [comment]
I opened #470 for this, but I noticed something and I'd like for you to confirm (or reject) it. As described [here](https://deploy-preview-470--terraform-docs.netlify.app/user-guide/configuration/#template-comment), it seems there must be an empty line before the end comment otherwise it will be processed as a link with text of `//`.

```
output:
  file: README.md
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)    
    {{ .Content }}
                             <--- this empty line seems to be mandatory
    [//]: # (END_TF_DOCS)    
```

That said, this is not blocking the PR in no way, because at the end of the day the content of `template` will be provided by user, so you can modify it (add empty line, or remove it if not needed) as you see fit.
