### ISSUE TITLE
markdown producing some sections in html styles

### ISSUE THREAD

**Issue by drewmullen** [terraform-docs/terraform-docs#500]
### Describe the bug

some sections are coming out with html like formatting:

Resources is the only section that comes out correctly

```
$ terraform-docs markdown ./

## Requirements

| Name | Version |
|------|---------|
| <a name="requirement_terraform"></a> [terraform](#requirement\_terraform) | >= 0.14.6 |
| <a name="requirement_aws"></a> [aws](#requirement\_aws) | 3.38.0 |

...

## Resources

| Name | Type |
|------|------|
| [aws_cloudtrail.centralized_cloudtrail](https://registry.terraform.io/providers/hashicorp/aws/3.38.0/docs/resources/cloudtrail) | resource |

...

## Outputs

| Name | Description |
|------|-------------|
| <a name="output_logging_acnt"></a> [logging\_acnt](#output\_logging\_acnt) | Account ID for the logging account |
| <a name="output_non_master_acnts"></a> [non\_master\_acnts](#output\_non\_master\_acnts) | Block of all non-master accounts managed by the organization |
```

### How can we reproduce it?

Open to ideas...

tried terraform-docs 0.12.1 and tried downgrading terraform to 14.x

### Environment information

```
$ terraform-docs --version
terraform-docs version v0.13.0 darwin/amd64 BuildDate: 2021-05-01T01:04:33+0100

$ terraform version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0

macos
```

**Comment by khos2ow** [comment]
You are absolutely right, these html codes are for markdown anchors and the only way to do them are with `<a>` tag.

> why is it default true?

We decided to enable them by default because it's a very popular and practical feature to have.

> why dosent it produce anchors for resources section?

Main reason was because resources are clickable links of their own.

**Comment by drewmullen** [comment]
> We decided to enable them by default because it's a very popular and practical feature to have.

but markdown doesnt render html? sorry maybe im missing something... 

> Main reason was because resources are clickable links of their own.

why not just use the markdown style links by default for all sections?

also i noticed that even with anchors off im still getting some html tags in variable lists:

```
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| account\_id | master account id | `string` | n/a | yes |
| account\_list | This parameter will make OUs and accounts. Its a nested map where data represents account\_name: ou\_name | `map(string)` | <pre>{<br>  "dev": "dev",<br>  "logging": "core",<br>  "network": "shared_services",<br>  "prod": "prod",<br>  "stage": "stage"<br>}</pre> | no |
```

**Comment by rslotte** [comment]
Am also seeing the `<br>` and `<pre>` tags when using `anchor=false`. 

Would be great to be able to disable these as they are causing issues when pushing markdown to our documentation portal.

**Comment by drewmullen** [comment]
@khos2ow can you confirm if this is a bug? https://github.com/terraform-docs/terraform-docs/issues/500#issuecomment-835362547

if there is a way to remove the `<br>` `<pre>` tags i can close this issue

**Comment by khos2ow** [comment]
> why not just use the markdown style links by default for all sections

Technically we are using markdown style links (i.e. to construct the link. for example `[logging\_acnt](#output\_logging\_acnt)`) but that has to point to _something_ (well to be precise itself) which that is being constructed by a [named anchor](https://dev.to/stephencweiss/named-anchors-markdown-2hm5) (e.g. `<a name="output_logging_acnt"></a>`).

> adding html to .md files just breaks the formatting because markdown doesnt support rending html tags

Technically you are correct for pure Markdown specification, but other engines built on top of Markdown are capable of rendering these properly, for example GitHub flavor, GitLab flavor, and etc.

> Am also seeing the `<br>` and `<pre>` tags when using anchor=false

This is because the nature of markdown table and multi-line text inside a cell. There is no other way to do it and have the multi-line representation intact, [this](https://alvinalexander.com/text/how-put-multiple-lines-markdown-table-cell-multiline-table/) and [this](https://stackoverflow.com/questions/24190085/markdown-multiline-code-blocks-in-tables-when-rows-have-to-be-specified-with-one) for reference. The only way to not use `<pre>` and `<br>` is to just show it in one line. For example:

```md
| account\_list | List of accounts | `map(string)` | `{  "dev": "dev",  "logging": "core",  "network": "shared_services",  "prod": "prod",  "stage": "stage" }` | no |
```

The result can be found in this [gist](https://gist.github.com/khos2ow/f2669a9a536eb0d2f7aa340f76cd367c), which ultimately becomes a personal choice of human readability vs markdown lint, which I completely understand both.

What I can think of and suggest is to add a new flag/config, e.g. `--use-html bool` or similar, to either use HTML tags or not at all.

**Comment by drewmullen** [comment]
`terraform fmt` does seem to accept single or multi-line maps. personally, i much prefer the readability of multi-line. when its 1 or 2 items in a map, nbd. but if you have 5+ then it becomes very unruly 

i would be in favor of a `--use-html false` feature option

**Comment by khos2ow** [comment]
#505 should fix this. Note that the new flag is called `--html bool` and it only controls items' attributes (e.g. description, type, default, etc).

If you want the generated output doesn't have any html tags at all you need to use `--html=false --anchor=false` both at the same time.

**Comment by drewmullen** [comment]
@khos2ow AWESOME! thanks a ton!
