### ISSUE TITLE
Generate docs for a packer hcl

### ISSUE THREAD

**Issue by nitrocode** [terraform-docs/terraform-docs#522]
### What problem are you facing?

Trying to generate hcl docs for a packer script

### How could terraform-docs help solve your problem?

I realize that `terraform` is in the title, however if `terraform-docs` reads hcl and the variables for a `packer` script are also in hcl, then how come this does not work ? or should this be a separate tool to generate `packer-docs` ?

https://github.com/spacelift-io/spacelift-worker-image/blob/main/spacelift.pkr.hcl

```shell
terraform-docs markdown .
```

I'm told if the file is renamed so that it ends with `.tf`, then `terraform-docs` does generate the input variables correctly in markdown. If so, is there a switch I can use to get the tool to read a non standard named hcl file?

**Comment by zf-hf** [comment]
This would be really rad to have implemented.

**Comment by khos2ow** [comment]
terraform-docs internally uses [terraform-config-inspect](https://github.com/terraform-docs/terraform-config-inspect) to read and parse the configuration. This is a pure clone of the upstream, which gives us some flexibility to enhance it if needed as this is considered feature complete from upstream maintainers.

`terraform-config-inspect` only reads `.tf` and `.tf.json` files:

https://github.com/terraform-docs/terraform-config-inspect/blob/b932ca5358a6017370f929eb8dd817e63cc6fde9/tfconfig/load.go#L125-L133

I think the easiest way to see if it makes sense to put an effort on this is for any of you guys to convert your `.pkr.hcl` config to either of `.tf` or `.tf.json` to see how it behaves. Then if successful, we can just simple add `.hcl` to allowed file types to `terraform-config-inspect`.

**Comment by aston-r** [comment]
@khos2ow 

I just coped the variables.pkr.hcl to variables.tf and successfully generated the doc by terraform-docs.  For sure  I have some empty sections like resources, modules, outputs since packer does not have such  functionality, but input section is correct.  Also in the future, it would be nice to parse https://github.com/hashicorp/packer-plugin-amazon/blob/main/docs/builders/index.mdx#how-to-use-this-plugin

Also as far as I know, hashicorp uses the same HCL engine for packer and terraform, so variables definitions  are the same: https://www.packer.io/guides/hcl/variables

**Comment by khos2ow** [comment]
That's great news @aston-r, thank you for testing out!
