### ISSUE TITLE
Do not use comments as variable description

### ISSUE THREAD

**Issue by poojitha-bikki** [terraform-docs/terraform-docs#552]
### Describe the bug

I have a variables.tf file with `# some comment` and then variables definitions follow
When I generate docs, the comment is used as variable description. I want to avoid that. Is there a config setting I can use to prevent this ?

### How can we reproduce it?

1. Create `variables.tf` with definition
```
# some comment
variable "var1" {
}
```
2. Run 
```
▶ terraform-docs markdown --output-check --show inputs ./
```
Input section will be rendered.

 Output is as follows:
```

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | some comment | `any` | n/a | yes |
```
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | some comment | `any` | n/a | yes |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | n/a | `any` | n/a | yes |

### Environment information

- terraform-docs version (use `terraform-docs --version`):
```
▶ terraform-docs version                                          

terraform-docs version v0.15.0 darwin/amd64
```
- OS (e.g. Windows, MacOS): MacOS

**Comment by khos2ow** [comment]
This happens, exactly as you described, because terraform-docs will attempt to read the leading comment as an description of the item. But, the conventions for them to be picked up are:

- line(s) should start with `#` or `//`. AND
- no empty line(s) between last line of comment and the definition of the item

So, to do what you want you can do one of the followings:

- empty line between comment and variable
 
  ```
  # some comment

  variable "var1" {
  }
  ```

- same as above different comment style
 
  ```
  // some comment

  variable "var1" {
  }
  ```

- you can use `/* */` style instead **without** empty line
 
  ```
  /* some comment */
  variable "var1" {
  }
  ```

Does any of these approaches work for you?

**Comment by poojitha-bikki** [comment]
@khos2ow Thank you. I've already tried inserting a new line and it skips the comment. But we have several modules, so was wondering instead of changing the TF files, if there is a config setting I can specify to not process the comments. It sounds like we have go with the workaround of inserting a new line or using block comment style for now.

**Comment by khos2ow** [comment]
That's a fair point, we definitely can add a new settings for it, something like `read-comment: true|false`.

**Comment by poojitha-bikki** [comment]
I'm working on this issue.
